export const timesCopa = [
  {
    id: 1,
    nome: "Catar",
    grupo: "A",
    forca: 70,
    ataque: 69,
    meio: 70,
    defesa: 71,
    escudo: "https://flagcdn.com/w160/qa.png",
    cor: "#8a1538",
    corSecundaria: "#5d0e25",
  },
  {
    id: 2,
    nome: "Equador",
    grupo: "A",
    forca: 78,
    ataque: 77,
    meio: 78,
    defesa: 79,
    escudo: "https://flagcdn.com/w160/ec.png",
    cor: "#ffda00",
    corSecundaria: "#0057b7",
  },
  {
    id: 3,
    nome: "Senegal",
    grupo: "A",
    forca: 81,
    ataque: 80,
    meio: 80,
    defesa: 83,
    escudo: "https://flagcdn.com/w160/sn.png",
    cor: "#009e60",
    corSecundaria: "#fdef42",
  },
  {
    id: 4,
    nome: "Holanda",
    grupo: "A",
    forca: 87,
    ataque: 86,
    meio: 89,
    defesa: 86,
    escudo: "https://flagcdn.com/w160/nl.png",
    cor: "#ae1c28",
    corSecundaria: "#1e4785",
  },

  {
    id: 5,
    nome: "Inglaterra",
    grupo: "B",
    forca: 89,
    ataque: 90,
    meio: 88,
    defesa: 89,
    escudo: "https://flagcdn.com/w160/gb-eng.png",
    cor: "#cf142b",
    corSecundaria: "#00247d",
  },
  {
    id: 6,
    nome: "Irã",
    grupo: "B",
    forca: 75,
    ataque: 73,
    meio: 75,
    defesa: 77,
    escudo: "https://flagcdn.com/w160/ir.png",
    cor: "#239f40",
    corSecundaria: "#da0000",
  },
  {
    id: 7,
    nome: "Estados Unidos",
    grupo: "B",
    forca: 80,
    ataque: 78,
    meio: 82,
    defesa: 80,
    escudo: "https://flagcdn.com/w160/us.png",
    cor: "#3c3b6e",
    corSecundaria: "#b22234",
  },
  {
    id: 8,
    nome: "País de Gales",
    grupo: "B",
    forca: 79,
    ataque: 81,
    meio: 79,
    defesa: 77,
    escudo: "https://flagcdn.com/w160/gb-wls.png",
    cor: "#c8102e",
    corSecundaria: "#00ab39",
  },

  {
    id: 9,
    nome: "Argentina",
    grupo: "C",
    forca: 91,
    ataque: 94,
    meio: 91,
    defesa: 88,
    escudo: "https://flagcdn.com/w160/ar.png",
    cor: "#75aadb",
    corSecundaria: "#f5f5f5",
  },
  {
    id: 10,
    nome: "Arábia Saudita",
    grupo: "C",
    forca: 73,
    ataque: 71,
    meio: 73,
    defesa: 75,
    escudo: "https://flagcdn.com/w160/sa.png",
    cor: "#006c35",
    corSecundaria: "#004d26",
  },
  {
    id: 11,
    nome: "México",
    grupo: "C",
    forca: 81,
    ataque: 80,
    meio: 82,
    defesa: 81,
    escudo: "https://flagcdn.com/w160/mx.png",
    cor: "#006847",
    corSecundaria: "#ce1126",
  },
  {
    id: 12,
    nome: "Polônia",
    grupo: "C",
    forca: 82,
    ataque: 85,
    meio: 80,
    defesa: 81,
    escudo: "https://flagcdn.com/w160/pl.png",
    cor: "#dc143c",
    corSecundaria: "#ffffff",
  },

  {
    id: 13,
    nome: "França",
    grupo: "D",
    forca: 90,
    ataque: 93,
    meio: 90,
    defesa: 87,
    escudo: "https://flagcdn.com/w160/fr.png",
    cor: "#002654",
    corSecundaria: "#ed2939",
  },
  {
    id: 14,
    nome: "Austrália",
    grupo: "D",
    forca: 76,
    ataque: 75,
    meio: 76,
    defesa: 77,
    escudo: "https://flagcdn.com/w160/au.png",
    cor: "#00008b",
    corSecundaria: "#ff0000",
  },
  {
    id: 15,
    nome: "Dinamarca",
    grupo: "D",
    forca: 83,
    ataque: 82,
    meio: 84,
    defesa: 83,
    escudo: "https://flagcdn.com/w160/dk.png",
    cor: "#c8102e",
    corSecundaria: "#f5f5f5",
  },
  {
    id: 16,
    nome: "Tunísia",
    grupo: "D",
    forca: 74,
    ataque: 73,
    meio: 74,
    defesa: 75,
    escudo: "https://flagcdn.com/w160/tn.png",
    cor: "#e70013",
    corSecundaria: "#ffffff",
  },

  {
    id: 17,
    nome: "Espanha",
    grupo: "E",
    forca: 87,
    ataque: 85,
    meio: 91,
    defesa: 85,
    escudo: "https://flagcdn.com/w160/es.png",
    cor: "#c60b1e",
    corSecundaria: "#ffc400",
  },
  {
    id: 18,
    nome: "Costa Rica",
    grupo: "E",
    forca: 74,
    ataque: 72,
    meio: 74,
    defesa: 76,
    escudo: "https://flagcdn.com/w160/cr.png",
    cor: "#002b7f",
    corSecundaria: "#ce1126",
  },
  {
    id: 19,
    nome: "Alemanha",
    grupo: "E",
    forca: 86,
    ataque: 87,
    meio: 88,
    defesa: 83,
    escudo: "https://flagcdn.com/w160/de.png",
    cor: "#000000",
    corSecundaria: "#dd0000",
  },
  {
    id: 20,
    nome: "Japão",
    grupo: "E",
    forca: 80,
    ataque: 79,
    meio: 81,
    defesa: 80,
    escudo: "https://flagcdn.com/w160/jp.png",
    cor: "#bc002d",
    corSecundaria: "#ffffff",
  },

  {
    id: 21,
    nome: "Bélgica",
    grupo: "F",
    forca: 86,
    ataque: 89,
    meio: 86,
    defesa: 83,
    escudo: "https://flagcdn.com/w160/be.png",
    cor: "#000000",
    corSecundaria: "#fdda24",
  },
  {
    id: 22,
    nome: "Canadá",
    grupo: "F",
    forca: 76,
    ataque: 78,
    meio: 76,
    defesa: 74,
    escudo: "https://flagcdn.com/w160/ca.png",
    cor: "#ff0000",
    corSecundaria: "#ffffff",
  },
  {
    id: 23,
    nome: "Marrocos",
    grupo: "F",
    forca: 82,
    ataque: 80,
    meio: 82,
    defesa: 84,
    escudo: "https://flagcdn.com/w160/ma.png",
    cor: "#c1272d",
    corSecundaria: "#006233",
  },
  {
    id: 24,
    nome: "Croácia",
    grupo: "F",
    forca: 85,
    ataque: 84,
    meio: 88,
    defesa: 83,
    escudo: "https://flagcdn.com/w160/hr.png",
    cor: "#171796",
    corSecundaria: "#ff0000",
  },

  {
    id: 25,
    nome: "Brasil",
    grupo: "G",
    forca: 93,
    ataque: 95,
    meio: 92,
    defesa: 92,
    escudo: "https://flagcdn.com/w160/br.png",
    cor: "#009c3b",
    corSecundaria: "#ffdf00",
  },
  {
    id: 26,
    nome: "Sérvia",
    grupo: "G",
    forca: 79,
    ataque: 82,
    meio: 78,
    defesa: 77,
    escudo: "https://flagcdn.com/w160/rs.png",
    cor: "#c6363c",
    corSecundaria: "#0c4076",
  },
  {
    id: 27,
    nome: "Suíça",
    grupo: "G",
    forca: 82,
    ataque: 81,
    meio: 83,
    defesa: 82,
    escudo: "https://flagcdn.com/w160/ch.png",
    cor: "#d52b1e",
    corSecundaria: "#f0f0f0",
  },
  {
    id: 28,
    nome: "Camarões",
    grupo: "G",
    forca: 77,
    ataque: 78,
    meio: 76,
    defesa: 77,
    escudo: "https://flagcdn.com/w160/cm.png",
    cor: "#007a5e",
    corSecundaria: "#ce1126",
  },

  {
    id: 29,
    nome: "Portugal",
    grupo: "H",
    forca: 88,
    ataque: 91,
    meio: 87,
    defesa: 86,
    escudo: "https://flagcdn.com/w160/pt.png",
    cor: "#006600",
    corSecundaria: "#ff0000",
  },
  {
    id: 30,
    nome: "Gana",
    grupo: "H",
    forca: 75,
    ataque: 77,
    meio: 74,
    defesa: 74,
    escudo: "https://flagcdn.com/w160/gh.png",
    cor: "#006b3f",
    corSecundaria: "#fcd116",
  },
  {
    id: 31,
    nome: "Uruguai",
    grupo: "H",
    forca: 84,
    ataque: 87,
    meio: 83,
    defesa: 82,
    escudo: "https://flagcdn.com/w160/uy.png",
    cor: "#0038a8",
    corSecundaria: "#f9f9f9",
  },
  {
    id: 32,
    nome: "Coreia do Sul",
    grupo: "H",
    forca: 76,
    ataque: 75,
    meio: 78,
    defesa: 75,
    escudo: "https://flagcdn.com/w160/kr.png",
    cor: "#c70000",
    corSecundaria: "#003478",
  },
];
